Numpy Practice 


In [1]:
import numpy as np 
a=np.array([1,2,3])
print(a)
print(a.ndim)
# 1-D

[1 2 3]
1


In [11]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print()
print(b.ndim)
# 2 D      

[[1 2 3]
 [4 5 6]]

2


In [2]:
import numpy as np 
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print()
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

2


In [8]:
c=np.array(100)
print(c)
print()
print(c.ndim)
# 0- D

100

0


In [13]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)
print()
print(d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2])

3


In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print( arr[0, 0])
print( arr[0, 1])
print( arr[0, 2])
print( arr[0, 3])
print( arr[0, 4])
print()
print( arr[1, 0])
print( arr[1, 1])
print( arr[1, 2])
print( arr[1, 3])
print( arr[1, 4])

1
2
3
4
5

6
7
8
9
10


In [34]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 0, 0])
print(arr[0, 0, 1])
print(arr[0, 0, 2])
print()
print(arr[0, 1, 0])
print(arr[0, 1, 1])
print(arr[0, 1, 2])
print()
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print()
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])

1
2
3

4
5
6

7
8
9

10
11
12


In [3]:
v=np.array([1,2,3,4,5,6,7,8])
print(v[0])

1


In [4]:
v[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
v[3:6]

array([4, 5, 6])

In [6]:
v[1:3]

array([2, 3])

In [7]:
v[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
v[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
import numpy as np 
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[:,1:2]


array([[2],
       [5],
       [8]])

In [10]:
matrix[:,2:2]

array([], shape=(3, 0), dtype=int32)

In [15]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[:,2:3]

array([[3],
       [6],
       [9]])

In [16]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[-3:-1,-3:-2]

array([[1],
       [4]])

In [17]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix.shape

(4, 3)

In [18]:
matrix.size

12

In [19]:
matrix.ndim

2

In [20]:
print(np.max(matrix))

12


In [21]:
print(np.min(matrix))

1


In [22]:
print(np.max(matrix,axis=0))

[10 11 12]


In [23]:
print(np.max(matrix,axis=1))

[ 3  6  9 12]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [25]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [27]:
# copy 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = arr.copy()
arr[0] = 42

print(arr)
print(new_arr)

[42  2  3  4  5]
[1 2 3 4 5]


In [28]:
# view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [29]:
# Make a view, change the view, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [30]:
# Make a copy, change the copy, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 31

print(arr)
print(x)

[1 2 3 4 5]
[31  2  3  4  5]


In [31]:
# Every NumPy array has the attribute base that returns None if the array owns the data.

# Otherwise, the base  attribute refers to the original object.

# Example
# Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [32]:
# Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [33]:
# Reshape From 1-D to 2-D
# ExampleGet your own Python Server
# Convert the following 1-D array with 12 elements into a 2-D array.

# The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
# Reshape From 1-D to 3-D
# Example
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [36]:
# iteration
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


print()

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]

1
2
3
4
5
6


In [37]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.random.random((3,4))

array([[0.53113508, 0.48768667, 0.13268734, 0.73809969],
       [0.91711931, 0.81330677, 0.12355084, 0.57770877],
       [0.69609803, 0.65637187, 0.46777828, 0.04568012]])

In [45]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [47]:
np.linspace(-10,100,10)

array([-10.        ,   2.22222222,  14.44444444,  26.66666667,
        38.88888889,  51.11111111,  63.33333333,  75.55555556,
        87.77777778, 100.        ])

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])